stages:
  mystage:
    cmd: python train.py
    deps:
    - data
    - train.py
    metrics:
    - metrics.txt:
        cache: false
    plots:
    - plots.png:  # Si estás generando 'plots.png' desde tu script
        cache: false
